# Librerias

In [1]:
from sqlalchemy import create_engine
import pandas as pd

# Conexion y carga

In [2]:
engine = create_engine("postgresql://ds_user:ds_pass@localhost:5432/ds_db")

# cargar clean
df = pd.read_sql("SELECT * FROM clean_load", engine)

df["datetime"] = pd.to_datetime(df["datetime"])
df = df.sort_values("datetime")
df

                  datetime   aep_mw
0      2004-10-01 01:00:00  12379.0
1      2004-10-01 02:00:00  11935.0
2      2004-10-01 03:00:00  11692.0
3      2004-10-01 04:00:00  11597.0
4      2004-10-01 05:00:00  11681.0
...                    ...      ...
121291 2018-08-02 20:00:00  17673.0
121292 2018-08-02 21:00:00  17303.0
121293 2018-08-02 22:00:00  17001.0
121294 2018-08-02 23:00:00  15964.0
121295 2018-08-03 00:00:00  14809.0

[121296 rows x 2 columns]

# Features de tiempo

In [4]:
df["hour"] = df["datetime"].dt.hour
df["dayofweek"] = df["datetime"].dt.dayofweek
df["is_weekend"] = df["dayofweek"].isin([5,6]).astype(int)
df

                  datetime   aep_mw  hour  dayofweek  is_weekend
0      2004-10-01 01:00:00  12379.0     1          4           0
1      2004-10-01 02:00:00  11935.0     2          4           0
2      2004-10-01 03:00:00  11692.0     3          4           0
3      2004-10-01 04:00:00  11597.0     4          4           0
4      2004-10-01 05:00:00  11681.0     5          4           0
...                    ...      ...   ...        ...         ...
121291 2018-08-02 20:00:00  17673.0    20          3           0
121292 2018-08-02 21:00:00  17303.0    21          3           0
121293 2018-08-02 22:00:00  17001.0    22          3           0
121294 2018-08-02 23:00:00  15964.0    23          3           0
121295 2018-08-03 00:00:00  14809.0     0          4           0

[121296 rows x 5 columns]

# Lags

In [5]:
df["lag_1"] = df["aep_mw"].shift(1)
df["lag_24"] = df["aep_mw"].shift(24)
df["lag_168"] = df["aep_mw"].shift(168)
df

,datetime,aep_mw,hour,dayofweek,is_weekend,lag_1,lag_24,lag_168
0,2004-10-01 01:00:00,12379.0,1,4,0,NaN,NaN,NaN
1,2004-10-01 02:00:00,11935.0,2,4,0,12379.0,NaN,NaN
2,2004-10-01 03:00:00,11692.0,3,4,0,11935.0,NaN,NaN
3,2004-10-01 04:00:00,11597.0,4,4,0,11692.0,NaN,NaN
4,2004-10-01 05:00:00,11681.0,5,4,0,11597.0,NaN,NaN
...,...,...,...,...,...,...,...,...
121291,2018-08-02 20:00:00,17673.0,20,3,0,18118.0,16579.0,19006.0
121292,2018-08-02 21:00:00,17303.0,21,3,0,17673.0,16457.0,18322.0
121293,2018-08-02 22:00:00,17001.0,22,3,0,17303.0,16197.0,17804.0
121294,2018-08-02 23:00:00,15964.0,23,3,0,17001.0,15259.0,16530.0
121295,2018-08-03 00:00:00,14809.0,0,4,0,15964.0,14125.0,15127.0

# Rolling

In [6]:
df["rolling_24"] = df["aep_mw"].shift(1).rolling(24).mean()
df["rolling_168"] = df["aep_mw"].shift(1).rolling(168).mean()
df

,datetime,aep_mw,hour,dayofweek,is_weekend,lag_1,lag_24,lag_168,rolling_24,rolling_168
0,2004-10-01 01:00:00,12379.0,1,4,0,NaN,NaN,NaN,NaN,NaN
1,2004-10-01 02:00:00,11935.0,2,4,0,12379.0,NaN,NaN,NaN,NaN
2,2004-10-01 03:00:00,11692.0,3,4,0,11935.0,NaN,NaN,NaN,NaN
3,2004-10-01 04:00:00,11597.0,4,4,0,11692.0,NaN,NaN,NaN,NaN
4,2004-10-01 05:00:00,11681.0,5,4,0,11597.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
121291,2018-08-02 20:00:00,17673.0,20,3,0,18118.0,16579.0,19006.0,15543.958333,15018.565476
121292,2018-08-02 21:00:00,17303.0,21,3,0,17673.0,16457.0,18322.0,15589.541667,15010.630952
121293,2018-08-02 22:00:00,17001.0,22,3,0,17303.0,16197.0,17804.0,15624.791667,15004.565476
121294,2018-08-02 23:00:00,15964.0,23,3,0,17001.0,15259.0,16530.0,15658.291667,14999.785714
121295,2018-08-03 00:00:00,14809.0,0,4,0,15964.0,14125.0,15127.0,15687.666667,14996.416667

# Eliminar Nulos

In [7]:
df = df.dropna()
df

,datetime,aep_mw,hour,dayofweek,is_weekend,lag_1,lag_24,lag_168,rolling_24,rolling_168
168,2004-10-08 01:00:00,12468.0,1,4,0,13271.0,12484.0,12379.0,14450.333333,13870.315476
169,2004-10-08 02:00:00,12046.0,2,4,0,12468.0,12054.0,11935.0,14449.666667,13870.845238
170,2004-10-08 03:00:00,11749.0,3,4,0,12046.0,11745.0,11692.0,14449.333333,13871.505952
171,2004-10-08 04:00:00,11784.0,4,4,0,11749.0,11757.0,11597.0,14449.500000,13871.845238
172,2004-10-08 05:00:00,11919.0,5,4,0,11784.0,12041.0,11681.0,14450.625000,13872.958333
...,...,...,...,...,...,...,...,...,...,...
121291,2018-08-02 20:00:00,17673.0,20,3,0,18118.0,16579.0,19006.0,15543.958333,15018.565476
121292,2018-08-02 21:00:00,17303.0,21,3,0,17673.0,16457.0,18322.0,15589.541667,15010.630952
121293,2018-08-02 22:00:00,17001.0,22,3,0,17303.0,16197.0,17804.0,15624.791667,15004.565476
121294,2018-08-02 23:00:00,15964.0,23,3,0,17001.0,15259.0,16530.0,15658.291667,14999.785714
121295,2018-08-03 00:00:00,14809.0,0,4,0,15964.0,14125.0,15127.0,15687.666667,14996.416667

# guardar en SQL

In [8]:
df.to_sql("features_hourly", engine, if_exists="replace", index=False)

print("features_hourly lista")

features_hourly lista